export const sectors = [
  {
    Name: "Agriculture",
    Code: "AG",
    Industries: [
      "Crop Production",
      "Livestock Farming",
      "Agricultural Services",
      "Animal Husbandry",
    ],
    Departments: [
      "Crop Management",
      "Farm Operations",
      "Agricultural Engineering",
      "Marketing",
      "Sales",
    ],
  },
  {
    Name: "Construction",
    Code: "CN",
    Industries: [
      "Building Construction",
      "Civil Engineering",
      "Speciality Trade Contractors",
    ],
    Departments: [
      "Project Management",
      "Architecture",
      "Engineering",
      "Procurement",
      "Quality Control",
      "Safety",
    ],
  },
  {
    Name: "Education",
    Code: "ED",
    Industries: ["Primary", "Secondary", "Higher", "Online"],
    Departments: [
      "Curriculum Development",
      "Instructional Design",
      "Student Affairs",
      "Admissions",
      "Finance",
      "Library Services",
    ],
  },
  {
    Name: "Energy",
    Code: "EN",
    Industries: ["Oil and Gas", "Renewable Energy", "Utilities"],
    Departments: [
      "Exploration",
      "Production",
      "Refining",
      "Distribution",
      "Research and Development",
      "Regulatory Compliance",
    ],
  },
  {
    Name: "Finance",
    Code: "FC",
    Industries: ["Banking", "Securities", "Insurance", "Financial Services"],
    Departments: [
      "Investment Banking",
      "Risk Management",
      "Retail Banking",
      "Asset Management",
      "Compliance",
      "Accounting",
    ],
  },
  {
    Name: "Government",
    Code: "GV",
    Industries: ["Federal", "State", "Local"],
    Departments: [
      "Administration",
      "Public Works",
      "Law Enforcement",
      "Healthcare Services",
      "Education Services",
      "Revenue Collection",
    ],
  },
  {
    Name: "Health Care",
    Code: "HC",
    Industries: [
      "Hospitals",
      "Medical Services",
      "Pharmaceutical Manufacturing",
    ],
    Departments: [
      "Emergency Medicine",
      "Surgery",
      "Nursing",
      "Diagnostic Imaging",
      "Pharmacy",
      "Health Information Management",
    ],
  },
  {
    Name: "Hospitality",
    Code: "HP",
    Industries: ["Hotels", "Restraunts", "Travel Agencies"],
    Departments: [
      "Front Desk",
      "House Keeping",
      "Food and Beverage",
      "Event Planning",
      "Marketing",
      "Customer Service",
    ],
  },
  {
    Name: "Information Technology",
    Code: "IT",
    Industries: [
      "Software Development",
      "Hardware Manufacturing",
      "IT Services",
    ],
    Departments: [
      "Software Development",
      "Network Administration",
      "Cybersecurity",
      "Data Analytics",
      "Technical Support",
      "Quality Assurance",
    ],
  },
  {
    Name: "Manufacturing",
    Code: "MF",
    Industries: ["Food Processing", "Automotive", "Aerospace"],
    Departments: [
      "Production Planning",
      "Supply Chain Management",
      "Quality Control",
      "Research and Development",
      "Engineering",
      "maintenance",
    ],
  },
  {
    Name: "Non-Profit",
    Code: "NP",
    Industries: ["Charitable Organisations", "Foundations", "Advocacy Groups"],
    Departments: [
      "Fundraising",
      "Program Management",
      "Community Outreach",
      "Volunteer Coordination",
      "Grant Writing",
      "Public Relations",
    ],
  },
  {
    Name: "Transportaion",
    Code: "TP",
    Industries: ["Air", "Water", "Land"],
    Departments: [
      "Operations Management",
      "Logistics",
      "Safety Management",
      "Maintenance",
      "Customer Service",
      "Regulatory Compliance",
    ],
  },
];
